In [1]:
import numpy as np

In [2]:
myarray = np.array(["h","e","l","l","o"])
print(myarray)

['h' 'e' 'l' 'l' 'o']


In [11]:
arrayX = np.array([3,4,6,7,4,2,5,8,9,3,2,2,4,5,6,7,7,7,7,4,3,2,3,4,5,43,2,1])
print(arrayX.shape)

(28,)


In [12]:
n = arrayX.reshape(4,7)
print(n)

[[ 3  4  6  7  4  2  5]
 [ 8  9  3  2  2  4  5]
 [ 6  7  7  7  7  4  3]
 [ 2  3  4  5 43  2  1]]


In [14]:
print("My Array Shape:", n.shape)

my array shape: (4, 7)


In [15]:
print("My Array Dimension:", n.ndim)

my array dimension: 2


In [16]:
print("Data Type: ", n.dtype.name)

Data Type:  int32


In [17]:
print("Size Of My Array:", n.size)

Size Of My Array: 28


In [18]:
print("Type Of My Array:", type(n))

Type Of My Array: <class 'numpy.ndarray'>


In [20]:
array3= np.array([["h","e","y","!"],["You","look","gorgeous","today!"]])

In [21]:
print(array3)

[['h' 'e' 'y' '!']
 ['You' 'look' 'gorgeous' 'today!']]


In [22]:
array3.shape

(2, 4)

In [23]:
zeros= np.zeros((2,6))

In [24]:
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [26]:
zeros[0,0]=2
print(zeros)

[[2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
ones = np.ones((8,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.arange(2,24,4)

array([ 2,  6, 10, 14, 18, 22])

In [35]:
x= np.linspace(0,5,10)
print(x)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [37]:
a= np.array([4,6,2])
b= np.array([2,7,1])

print(a+b)
print(a*b)
print(b**2)

[ 6 13  3]
[ 8 42  2]
[ 4 49  1]


In [39]:
mylist= [3,5,7,1]
myarray = np.array([0,8,5,2])
print(mylist)
print(myarray)

[3, 5, 7, 1]
[0 8 5 2]


In [40]:
a = np.array([8,2,3])

In [47]:
b=a
c=a

In [48]:
b[1]=8
print(a,b,c)

[5 8 3] [5 8 3] [5 8 3]


In [49]:
a[1]=8
d=a.copy()
print(d)

[5 8 3]


In [50]:
d

array([5, 8, 3])

In [51]:
a

array([5, 8, 3])

In [52]:
a=np.array([3,6,2,8,2,1])
a[0]

3

In [53]:
a[0:5]

array([3, 6, 2, 8, 2])

In [54]:
a[::-1]

array([1, 2, 8, 2, 6, 3])

In [86]:
b=np.array([["n","i","s","r","e","e","n"],["B","o","u","t","a","^-^","!"]])
b

array([['n', 'i', 's', 'r', 'e', 'e', 'n'],
       ['B', 'o', 'u', 't', 'a', '^-^', '!']], dtype='<U3')

In [63]:
print(b[1,1])

o


In [64]:
print(b[:,3])

['r' 't']


In [68]:
b[:,6]

array(['n', '!'], dtype='<U3')

In [69]:
b[0,:]

array(['n', 'i', 's', 'r', 'e', 'e', 'n'], dtype='<U3')

In [77]:
b[1,0:6]

array(['B', 'o', 'u', 't', 'a', '^-^'], dtype='<U3')

In [78]:
b[-1,:]

array(['B', 'o', 'u', 't', 'a', '^-^', '!'], dtype='<U3')

In [79]:
b[:,-1]

array(['n', '!'], dtype='<U3')

In [80]:
b = b.ravel()
print(b)

['n' 'i' 's' 'r' 'e' 'e' 'n' 'B' 'o' 'u' 't' 'a' '^-^' '!']


In [87]:
b.T

array([['n', 'B'],
       ['i', 'o'],
       ['s', 'u'],
       ['r', 't'],
       ['e', 'a'],
       ['e', '^-^'],
       ['n', '!']], dtype='<U3')